[DEFAULT]
data_dir = "/cluster/work/users/egilron/wl-coref-ncc/tomls/saga01"
train_data = "/cluster/work/users/egilron/ncc/wl-ncc/bokmaal/bokmaal_train_head.jsonl"
dev_data = "/cluster/work/users/egilron/ncc/wl-ncc/bokmaal/bokmaal_development_head.jsonl"
test_data = "/cluster/work/users/egilron/ncc/wl-ncc/bokmaal/bokmaal_test_head.jsonl"
device = "cpu"
bert_model = "/cluster/shared/nlpl/data/vectors/latest/221/"
bert_window_size = 512
embedding_size = 20
sp_embedding_size = 64
a_scoring_batch_size = 512
hidden_size = 1024
n_hidden_layers = 1
max_span_len = 64
rough_k = 50
bert_finetune = false
dropout_rate = 0.3
bert_learning_rate = 1e-5
learning_rate = 0.0003
train_epochs = 20
bce_loss_weight = 0.5
conll_log_dir = "/cluster/work/users/egilron/wl-coref-ncc/tomls/saga01/conll_logs"

[saga01_000]
a_scoring_batch_size = 128

[saga01_001]
a_scoring_batch_size = 256

[saga01_002]
a_scoring_batch_size = 512

[DEFAULT.tokenizer_kwargs.roberta-large]
add_prefix_space = true

[DEFAULT.tokenizer_kwargs.spanbert-large-cased]
do_lower_case = false

[DEFAULT.tokenizer_kwargs.bert-large-cased]
do_lower_case = false
